package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"text/template"
)

// https://mholt.github.io/json-to-go/ で自動生成しています・
type AutoGenerated struct {
	Horoscope struct {
		Two018053 []struct {
			Content string `json:"content"`
			Item    string `json:"item"`
			Money   int    `json:"money"`
			Total   int    `json:"total"`
			Job     int    `json:"job"`
			Color   string `json:"color"`
			Day     json.Number    `json:"day"` //Stringとintの可能性があります
			Love    int    `json:"love"`
			Rank    int    `json:"rank"`
			Sign    string `json:"sign"`
		} `json:"2018/05/3"`
	} `json:"horoscope"`
}

// 自動生成終わり

// 表示するパラメータ
type Page struct {
	Content string
	Rank    int
	Sign    string
}

func fortuneTellingAPI() Page {
	url := "http://api.jugemkey.jp/api/horoscope/free/2018/5/3"

	resp, _ := http.Get(url) //TODO エラーハンドリグ
	defer resp.Body.Close()

	byteArray, _ := ioutil.ReadAll(resp.Body) //TODO エラーハンドリング
	jsonBytes := ([]byte)(string(byteArray))
	data := new(AutoGenerated)
	if err := json.Unmarshal(jsonBytes, data); err != nil {
		fmt.Println("JSON Unmarshal error:", err)
		return Page{"err",0,"err"} //TODO いい文言に変える
	}

	page := Page{data.Horoscope.Two018053[0].Content, data.Horoscope.Two018053[0].Rank, data.Horoscope.Two018053[0].Sign}
	return page
}

func viewHandler(w http.ResponseWriter, r *http.Request) {
	page := fortuneTellingAPI()
	tmpl, err := template.ParseFiles("layout.html") // ParseFilesを使う
	if err != nil {
		panic(err)
	}

	err = tmpl.Execute(w, page)
	if err != nil {
		panic(err)
	}
}

func main() {
	http.HandleFunc("/", viewHandler)
	http.ListenAndServe(":8080", nil)
}
